version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release
before_build:
- ps: >-
    nuget restore .\firenotes.sln
build:
  project: .\firenotes.sln
  verbosity: quiet